Newscoop\Package\Item:
    exclusion_policy: ALL
    properties:
        caption:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: caption
        type:
            expose: true
            read_only: true
            type: string
            access_type: public_method
            groups: ["details", "list"]
            serialized_name: type
        link:
            expose: true
            read_only: true
            type: image_uri
            groups: ["details", "list"]
            accessor:
                getter: getItem
            serialized_name: link
    virtual_properties:
        getImage:
            expose: true
            read_only: true
            type: thumbnail_uri
            groups: ["details", "list"]
            serialized_name: thumbnail
            since_version: 1.2